baseURL = "https://ikaqutami.github.io/"
languageCode = "id"
title = "Utami's Log"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
author = "Ika Utami"
description = "Blog tentang AI, Pendidikan, Penelitian, dan Teknologi"

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true

ShowArchives = true

[params.homeInfoParams]
Title = "Selamat Datang 👋"
Content = """
Berbagi tulisan tentang Artificial Intelligence, Pendidikan,
Penelitian, Teknologi, dan Pengabdian Masyarakat.
"""

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "Archive"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 40

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50